Instalaçôes:


pip install git+https://github.com/huggingface/transformers.git sentencepiece


pip install protobuf

#torch [Linux cuda 118 - VERIFICAR SEU SISTEMA (WIN / Linux / Mac)

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

In [ ]:
!pip install protobuf

Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (4.25.5)

In [ ]:
!pip install git+https://github.com/huggingface/transformers.git sentencepiece

Collecting git+https://github.com/huggingface/transformers.git
  Cloning https://github.com/huggingface/transformers.git to /tmp/pip-req-build-cp02l9u1
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /tmp/pip-req-build-cp02l9u1
  Resolved https://github.com/huggingface/transformers.git to commit 3a8eb74668e9c2cc563b2f5c62fac174797063e0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (0.2.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers==4.47.0.dev0) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.47.0.dev0) (0.26.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.47.0.dev0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.47.0.dev0) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.47.0.dev0) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.47.0.dev0) (2024.9.11)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.47.0.dev0) (2.32.3)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.10/dist-packages (from transformers==4.47.0.dev0) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.47.0.dev0) (0.4.5)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.47.0.dev0) (4.66.6)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers==4.47.0.dev0) (2024.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers==4.47.0.dev0) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.47.0.dev0) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.47.0.dev0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.47.0.dev0) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.47.0.dev0) (2024.8.30)
Building wheels for collected packages: transformers
  Building wheel for transformers (pyproject.toml) ... done
  Created wheel for transformers: filename=transformers-4.47.0.dev0-py3-none-any.whl size=10101071 sha256=91c27ce91659fc6a411a2db9cbab7df93537a298ae662b4bd1166e753a664b68
  Stored in directory: /tmp/pip-ephem-wheel-cache-speuud_h/wheels/e7/9c/5b/e1a9c8007c343041e61cc484433d512ea9274272e3fcbe7c16
Successfully built transformers
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 4.46.2
    Uninstalling transformers-4.46.2:
      Successfully uninstalled transformers-4.46.2
Successfully installed transformers-4.47.0.dev0

In [ ]:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu118
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.5.1+cu121)
Requirement already satisfied: torchvision in /usr/local/lib/python3.10/dist-packages (0.20.1+cu121)
Requirement already satisfied: torchaudio in /usr/local/lib/python3.10/dist-packages (2.5.1+cu121)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2024.10.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from torchvision) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision) (11.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (3.0.2)

In [ ]:
from transformers import AutoProcessor, SeamlessM4Tv2Model

processor = AutoProcessor.from_pretrained("facebook/seamless-m4t-v2-large")
model = SeamlessM4Tv2Model.from_pretrained("facebook/seamless-m4t-v2-large")

#from transformers import AutoProcessor, SeamlessM4Tv2ForTextToText
#model = SeamlessM4Tv2ForTextToText.from_pretrained("facebook/seamless-m4t-v2-large")
#processor = AutoProcessor.from_pretrained("facebook/seamless-m4t-v2-large")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

preprocessor_config.json:   0%|          | 0.00/1.78k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/19.7k [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.17M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/2.07k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.34k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/2.72k [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/211k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/4.24G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/9.91M [00:00<?, ?B/s]

In [ ]:
import pandas as pd

In [ ]:
import google.colab.drive as drive
drive.mount ('/content/drive')

Mounted at /content/drive

In [ ]:
# Define the credentials for the SeamlessM4Tv2 model
src_lang = "por"
tgt_lang = "eng"

In [ ]:
#Replace 'path/to/file.csv' with the actual path to your CSV file
path_csv_file = '/content/drive/MyDrive/Dados/Traducao/input_active_ing_translate_meta.csv'

In [ ]:
df = pd.read_csv(path_csv_file)

In [ ]:
df.head()

   id_active_ingredient                          active_ingredient
0                     1  EXTRATO FLUIDO DE CASCA DE LARANJA AMARGA
1                     2         EXTRATO FLUIDO DE PASSIFLORA ALATA
2                     3                        SALICILATO DE SÓDIO
3                     4                  TINTURA AGONIADA PLUMÉRIA
4                     5                     ACIDO ACETILSALICILICO

In [ ]:
# Function to translate text

def translate_text(text_ori):
    text_inputs = processor(text=text_ori, src_lang=src_lang, return_tensors="pt")
    output_tokens = model.generate(**text_inputs, tgt_lang=tgt_lang, generate_speech=False)
    translated_text = processor.decode(output_tokens[0].tolist()[0], skip_special_tokens=True)

    return translated_text

In [ ]:
# Loop to translate line by line and print
for index, row in df.iterrows():
    texto_original = row["active_ingredient"]

    texto_traduzido = translate_text(texto_original)
    print(f"Original: {texto_original} | Traduzido: {texto_traduzido}")

    # Atualizar o DataFrame com as traduções
    df.at[index, "active_ingredient_eng"] = texto_traduzido

Original: EXTRATO FLUIDO DE CASCA DE LARANJA AMARGA | Traduzido: Fluid extract from bitter orange peel
Original: EXTRATO FLUIDO DE PASSIFLORA ALATA | Traduzido: Extruded fluid of alata
Original: SALICILATO DE SÓDIO | Traduzido: Sodium salicylate
Original: TINTURA AGONIADA PLUMÉRIA | Traduzido: TINTURA AGONIADA PLUMÉRIA It is also known as TINTURA AGONIADA PLUMÉRIA
Original: ACIDO ACETILSALICILICO | Traduzido: Acetylsalicylic acid
Original: ACETATO DE ABIRATERONA | Traduzido: Acetate of abiraterone
Original: CLOTRIMAZOL | Traduzido: Clotrimazole and its derivatives
Original: BETAÍNA | Traduzido: Bethany, please.
Original: CITRATO DE COLINA | Traduzido: Cinnamon citrate
Original: DL-METIONINA | Traduzido: DL-methionine and its salts
Original: LEVOMETIONINA | Traduzido: Other medicinal products
Original: DIPIRONA | Traduzido: DIPRONA is the name of the country.
Original: ATENOLOL | Traduzido: The Athenol
Original: CLORTALIDONA | Traduzido: Cloridone and its derivatives
Original: CLORIDRATO DE DULOXETINA | Traduzido: Chloride of duloxetine
Original: HEDERA HELIX L. | Traduzido: HEDERA HELIX L. This is a list of people who have been awarded the Nobel Prize in Physiology or Medicine.
Original: CRATAEGUS RHIPIDOPHYLLA GAND. | Traduzido: The crataegus rhizophyllla is a type of crataegus.
Original: PASSIFLORA INCARNATA L. | Traduzido: Passyflora incarnata, also known as
Original: VALERIANA OFFICINALIS L. | Traduzido: Valeriana Officinalis L. was born in
Original: ACETATO DE RACEALFATOCOFEROL | Traduzido: Acetate of racalphatocoferol
Original: BETACAROTENO | Traduzido: Bettacarotene, also known as betacarotene
Original: OXIDO CUPRICO | Traduzido: Oxygenated copper
Original: RIBOFLAVINA | Traduzido: Riboflavina, also known as riboflavina
Original: SELENATO DE SÓDIO | Traduzido: Sodium selenate
Original: ÁCIDO ASCÓRBICO | Traduzido: Ascorbic acid

KeyboardInterrupt:

In [ ]:
# Display the first few rows of the DataFrame df
df.head()

,id_active_ingredient,active_ingredient,active_ingredient_eng
0,1,EXTRATO FLUIDO DE CASCA DE LARANJA AMARGA,Fluid extract from bitter orange peel
1,2,EXTRATO FLUIDO DE PASSIFLORA ALATA,Extruded fluid of alata
2,3,SALICILATO DE SÓDIO,Sodium salicylate
3,4,TINTURA AGONIADA PLUMÉRIA,TINTURA AGONIADA PLUMÉRIA It is also known as ...
4,5,ACIDO ACETILSALICILICO,Acetylsalicylic acid

In [ ]:
df.to_csv('/content/drive/MyDrive/Dados/Traducao/output_active_ing_translate_meta.csv', index=False)